### PR TITLE
Update passenv syntax for tox 4.0.8

### PR DESCRIPTION
**Pull request by ojustino**
Reacting to an upstream update by `tox`, as in spacetelescope/jdaviz#1916.

### CODE REVIEW

**Review by kecnry — APPROVED** [review]

**Comment by tepickering** [comment]
thanks! this change has bitten a lot of projects. there's a weird failure in the `oldestdeps` test. might be spurious or it might need a change in lowest supported version of something (likely `numpy`).

**Comment by ojustino** [comment]
I think the problem may have been that `oldestdeps` tests `specutils` all the way back to v1.7.0 even though we require v1.9.1 as of our last release. After updating the `oldestdeps` pin to v1.9.1 and resolving a few other version conflicts, I don't see the failure locally. Let's see how GitHub likes it...

**Comment by kecnry** [comment]
Do any of those require changes to the pins in `setup.cfg`?  Or will `specutils>=1.9.1` already require at least the min versions of astropy/numpy in the CI matrix?

**Comment by ojustino** [comment]
`specutils>=1.9.1` covers us with `astropy>=5.1`, which covers us with `numpy>=1.20`. I'm not sure about `matplotlib`, which is only in the "recommended" section of Astropy's setup file, but that shouldn't matter for the CI matrix, right?

**Pull request merged**
