### PR TITLE
Add citation and Zenodo badge

### LINKED ISSUE #108: DOC: Add CITATION file
As this package is now under review for becoming an Astropy coordinated package, could you add instructions on how to preferably cite this package and any relevant publications related to it; most conveniently by putting the info (possibly with BibTeX etc.) into a `CITATION` file?
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
for further recommendations.

### PR DESCRIPTION
**Pull request by tepickering**
A Zenodo DOI has been created for the `1.0.0` release and a badge pointing to that added to the `README` file. A `CITATION.cff` file has been added here that points to that DOI. I have thus far only added myself as an author in that file. I encourage other contributors to add their information to it either by editing the file directly in this PR or adding it later in a separate PR. 

Closes #108.

### CODE REVIEW

**Comment by pllim** [comment]
There are only 13 non-bot authors from the GitHub contributors (though that might not always be accurate): https://github.com/astropy/specreduce/graphs/contributors

1. @tepickering 
2. @ojustino 
3. @ibusko 
4. @kecnry 
5. @pllim 
6. @duytnguyendtn 
7. @simontorres 
8. @jehturner 
9. @crawfordsm 
10. @eteq 
11. @mfixstsci 
12. @jradavenport 
13. @lprichard

**Comment by tepickering** [comment]
that's still more than i want to fill in myself by hand 😆

**Comment by pllim** [comment]
I have pinged my STScI colleagues. For myself, I will opt out since my name probably appeared because of some routine Astropy patching, not as much as the actual "reduce" part.

**Comment by tepickering** [comment]
thanks to those who've added themselves to the author list! i'm off on holiday for the next week and would like to merge this when i return from that. if there is anyone still missing at that point, i'll fill things in as best as i can...

**Comment by tepickering** [comment]
doesn't look like anyone else has added themselves to the citation list in the past couple weeks. i'd like to call it good enough for now and merge this. more names can be added later via additional PRs...

**Pull request merged**
