### PR TITLE
Operation class

### PR DESCRIPTION
**Pull request by crawfordsm**
This is a pull request with an initial template of the SpecReduce class and an example using boxcar smoothing for the extraction.

### CODE REVIEW

**Comment by jradavenport** [comment]
this doesn't include `trace`, should we dump that too (recognizing there are some further ideas about trace that need to be implemented)

**Comment by eteq** [comment]
@jradavenport - as initially formulated the suggestion was made (I forget by who...) to "assume the trace object exists" to provide a minimal example of the `SpecreduceOperation` class, because we're thinking there's need for some sort of data object to hole the trace rather than just sending the raw trace function around.  But now that you say it perhaps it makes sense to include some trace to have working tests of this minimal example...

**Comment by eteq** [comment]
Another thought discussed in slack was to pull in the DRAGONS pipeline trace code as a test of the concept that the operations can be modular, so that might be an alternative trace code to use for the above as an experiment.

**Comment by tepickering** [comment]
in the interest of moving things forward i'm just going to go ahead and merge this and fix the issues in a new PR.

**Pull request merged**
