### PR TITLE
BLD: pin extension-helpers to 1.* following upstream recommendation

### PR DESCRIPTION
**Pull request by neutrinoceros**
Following https://github.com/astropy/extension-helpers/pull/72

### CODE REVIEW

**Comment by neutrinoceros** [comment]
The devdeps failure is unrelated. Please let me know if you need a hand with it, I'll be happy to help !

**Review by kecnry — APPROVED** [review]
Works for me - thanks!  Any concerns @tepickering?

**Comment by pllim** [comment]
Wait a minute, why is it even a build dependency here? I don't see any C-extension.

**Comment by neutrinoceros** [comment]
Indeed, thanks for catching this ! Superseded by #201

**Pull request closed without merging**
